# Generated by Django 2.1.1 on 2019-06-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20190623_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertracking',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertracking',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='user_tracking'),
        ),
    ]
