# Generated by Django 2.0.8 on 2019-07-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20190623_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
