# Generated by Django 2.0.8 on 2019-07-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_usuarios_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
