# Generated by Django 2.0.8 on 2019-07-01 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0030_auto_20190522_1508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Programagasto',
        ),
        migrations.DeleteModel(
            name='Programagastos',
        ),
    ]
