# Generated by Django 2.0.8 on 2019-07-01 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0031_auto_20190630_2121'),
    ]

    operations = [
        #migrations.DeleteModel(
        #    name='Centrodecosto1',
        #),
    ]
