# Generated by Django 2.0.8 on 2019-07-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0032_delete_centrodecosto1'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcotizacion',
            name='alert',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dcotizacion',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dcotizacion',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dcotizacion',
            name='end_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dcotizacion',
            name='end_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dcotizacion',
            name='endtask',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dcotizacion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dcotizacion',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dcotizacion',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='user_tracking'),
        ),
        migrations.AddField(
            model_name='dcotizacion',
            name='start_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dcotizacion',
            name='start_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dcotizacion',
            name='starttask',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dcotizacion',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='dgasto',
            name='alert',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dgasto',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dgasto',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dgasto',
            name='end_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dgasto',
            name='end_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dgasto',
            name='endtask',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dgasto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dgasto',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dgasto',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='user_tracking'),
        ),
        migrations.AddField(
            model_name='dgasto',
            name='start_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dgasto',
            name='start_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dgasto',
            name='starttask',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dgasto',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='dguia',
            name='alert',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dguia',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dguia',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dguia',
            name='end_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dguia',
            name='end_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dguia',
            name='endtask',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dguia',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dguia',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dguia',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='user_tracking'),
        ),
        migrations.AddField(
            model_name='dguia',
            name='start_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dguia',
            name='start_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dguia',
            name='starttask',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dguia',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='dliquidacion',
            name='alert',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dliquidacion',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dliquidacion',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dliquidacion',
            name='end_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dliquidacion',
            name='end_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dliquidacion',
            name='endtask',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dliquidacion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dliquidacion',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dliquidacion',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='user_tracking'),
        ),
        migrations.AddField(
            model_name='dliquidacion',
            name='start_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dliquidacion',
            name='start_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dliquidacion',
            name='starttask',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dliquidacion',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
