# Generated by Django 2.1.1 on 2019-07-10 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0034_auto_20190710_0043'),
        ('gestionapp', '0032_auto_20190710_0206'),
    ]

    operations = [
    ]
