# Generated by Django 2.1.1 on 2019-07-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0035_merge_20190710_1529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Centrodecosto1',
        ),
    ]
