# Generated by Django 2.0.8 on 2019-07-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0036_delete_centrodecosto1'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='categprov',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='categprov',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='categprov',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='transporte',
            name='categprov',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='idioma',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idioma',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='idioma',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='idioma',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
