# Generated by Django 2.0.8 on 2019-07-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0037_auto_20190713_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.IntegerField(default=0)),
                ('anulado', models.IntegerField(default=0)),
                ('fecregistro', models.DateField(blank=True, null=True)),
                ('aud_idusu', models.CharField(blank=True, max_length=30, null=True)),
                ('aud_feccre', models.DateTimeField(auto_now=True)),
                ('aud_fecmod', models.DateField(blank=True, null=True)),
                ('aud_feceli', models.DateField(blank=True, null=True)),
                ('posmapa', models.IntegerField(default=0)),
                ('codigo', models.CharField(blank=True, max_length=15, null=True)),
                ('ruc', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono1', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono2', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono3', models.CharField(blank=True, max_length=20, null=True)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('telcontacto', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=150, null=True)),
                ('contacto2', models.CharField(blank=True, max_length=100, null=True)),
                ('telcontacto2', models.CharField(blank=True, max_length=20, null=True)),
                ('correo2', models.CharField(blank=True, max_length=150, null=True)),
                ('contacto3', models.CharField(blank=True, max_length=100, null=True)),
                ('telcontacto3', models.CharField(blank=True, max_length=20, null=True)),
                ('correo3', models.CharField(blank=True, max_length=150, null=True)),
                ('contacto4', models.CharField(blank=True, max_length=100, null=True)),
                ('telcontacto4', models.CharField(blank=True, max_length=20, null=True)),
                ('correo4', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('paginaweb', models.CharField(blank=True, max_length=150, null=True)),
                ('tipocc', models.IntegerField(blank=True, default=0, null=True)),
                ('destipocc', models.CharField(blank=True, max_length=100, null=True)),
                ('condcompvent', models.CharField(blank=True, max_length=100, null=True)),
                ('banco_nombre1', models.CharField(blank=True, max_length=100, null=True)),
                ('banco_cuenta1', models.CharField(blank=True, max_length=100, null=True)),
                ('banco_nomdest1', models.CharField(blank=True, max_length=100, null=True)),
                ('banco_moneda1', models.CharField(blank=True, max_length=20, null=True)),
                ('banco_nombre2', models.CharField(blank=True, max_length=100, null=True)),
                ('banco_cuenta2', models.CharField(blank=True, max_length=100, null=True)),
                ('banco_nomdest2', models.CharField(blank=True, max_length=100, null=True)),
                ('banco_moneda2', models.CharField(blank=True, max_length=20, null=True)),
                ('fechanac', models.DateField(blank=True, help_text='Ingrese si esta activo u otro stado ', null=True)),
                ('fechaini', models.DateField(blank=True, null=True)),
                ('fechafin', models.DateField(blank=True, null=True)),
                ('grupo', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=50, null=True)),
                ('idioma', models.CharField(blank=True, max_length=80, null=True)),
                ('categprov', models.CharField(blank=True, max_length=80, null=True)),
                ('tipocontrato', models.CharField(blank=True, max_length=100, null=True)),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='guia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='chofer',
            name='foto1',
            field=models.ImageField(blank=True, null=True, upload_to='unidad'),
        ),
        migrations.AddField(
            model_name='chofer',
            name='tipocontrato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipocontrato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipocontrato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transporte',
            name='tipocontrato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='aniofab',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='cadsoat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='combustible',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='docantepena',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='docantepoli',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='docbrevete',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='doccursos',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='docdni',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='empresa',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='mantglp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='revtec',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='segveh',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='npasajeros',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
