# Generated by Django 2.0.8 on 2019-08-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0041_auto_20190802_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='brevete',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
