# Generated by Django 2.0.8 on 2019-09-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0045_auto_20190922_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcotizacion',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dcotizacion',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dgasto',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dguia',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dliquidacion',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
