# Generated by Django 2.0.8 on 2019-10-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0047_auto_20191004_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcotizacion',
            name='nombreguia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dgasto',
            name='nombreguia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dguia',
            name='nombreguia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dliquidacion',
            name='nombreguia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
