# Generated by Django 2.0.8 on 2019-11-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0048_auto_20191009_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcotizacion',
            name='ruc',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
