# Generated by Django 2.0.8 on 2019-11-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0049_auto_20191106_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcotizacion',
            name='ruc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
