# Generated by Django 2.0.8 on 2019-11-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0050_auto_20191106_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='ruc',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ruc',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='guia',
            name='ruc',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='ruc',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
