# Generated by Django 2.0.8 on 2019-11-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0051_auto_20191106_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='comonoscontacto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='comonoscontacto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='guia',
            name='comonoscontacto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='comonoscontacto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='transporte',
            name='comonoscontacto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
