# Generated by Django 2.0.8 on 2020-01-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0052_auto_20191117_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcotizacion',
            name='comonoscontacto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
